<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia 
                ixx="${(1/12) * mass * (3*radius*radius + length*length)}"
                ixy="0.0"
                ixz="0.0"
                iyy="${(1/12) * mass * (3*radius*radius + length*length)}"
                iyz="0.0"
                izz="${(1/2) * mass * (radius*radius)}" />
            </inertial>
    </xacro:macro>

    <xacro:macro name="insert_roller" params="parent reflect theta suffix wheel">
        <joint name="roller_${wheel}_${suffix}_joint" type="continuous">
            <origin xyz="${rim_radius*cos(theta)} ${rim_radius*sin(theta)} ${reflect*rim_height_offset+rim_height}" rpy="0.0 ${PI/2} ${theta-PI/2}"/>
            <parent link="${parent}"/>
            <child link="roller_${wheel}_${suffix}_link"/>
            <axis xyz="0.0 0.0 1.0"/>
            <dynamics friction="0.1"/>
        </joint>

        <link name="roller_${wheel}_${suffix}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find origin_description)/meshes/roller.stl" scale="0.001 0.001 0.001" />
                </geometry>
                <material name="silver"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find origin_description)/meshes/roller.stl" scale="0.001 0.001 0.001" />
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.003"/>
                <inertia ixx="5.3e-8"
                         ixy="0.0"
                         ixz="0.0"
                         iyy="8e-8"
                         iyz="0.0"
                         izz="8e-8"/>
            </inertial>

        </link>
        <gazebo reference="roller_${wheel}_${suffix}_link">
            <material>Gazebo/Green</material>
            <fdir1>1 0 0"</fdir1>
            <mu1>0.2</mu1>
            <mu2>0.1</mu2>
            <minDepth>0.001</minDepth>
        </gazebo>
    </xacro:macro>

	<xacro:macro name="wheel" params="parent suffix theta">
        <joint name="wheel_${suffix}_joint" type="continuous">
            <origin xyz="${chassis_innere_radius*cos(theta)} ${chassis_innere_radius*sin(theta)} 0.0" rpy="0.0 ${PI/2} ${theta}"/>
            <parent link="${parent}"/>
            <child link="wheel_${suffix}_link"/>
            <axis xyz="0.0 0.0 1.0"/>
        </joint>

        <link name="wheel_${suffix}_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find origin_description)/meshes/rim.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="silver"/>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="file://$(find origin_description)/meshes/rim.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <mass value="0.3495383475867773"/>
    			<inertia ixx="0.000247" iyy="0.00022" izz="0.000207" ixy="2.3e-05" iyz="0.0" ixz="1e-06"/>
            </inertial>
        </link>

        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${PI/18}" suffix="a1" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${2*PI/9+PI/18}" suffix="a2" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${4*PI/9+PI/18}" suffix="a3" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${2*PI/3+PI/18}" suffix="a4" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${8*PI/9+PI/18}" suffix="a5" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${10*PI/9+PI/18}" suffix="a6" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${4*PI/3+PI/18}" suffix="a7" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${14*PI/9+PI/18}" suffix="a8" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="1.0" theta="${16*PI/9+PI/18}" suffix="a9" wheel="${suffix}"/>


        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${17*PI/9+PI/18}" suffix="b1" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${PI/3+PI/18}" suffix="b2" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${5*PI/9+PI/18}" suffix="b3" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${7*PI/9+PI/18}" suffix="b4" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${PI+PI/18}" suffix="b5" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${11*PI/9+PI/18}" suffix="b6" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${13*PI/9+PI/18}" suffix="b7" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${5*PI/3+PI/18}" suffix="b8" wheel="${suffix}"/>
        <xacro:insert_roller parent="wheel_${suffix}_link" reflect="-1.0" theta="${PI/9+PI/18}" suffix="b9" wheel="${suffix}"/>

    </xacro:macro>

</robot>